### ISSUE TITLE
Audit log empty after logrotation

### ISSUE THREAD

**Issue by deeztek** [ITSec-Chile/Waf2Py#11]
All of a sudden, I'm getting the following error on a number of sites when I try to reload nginx:

**Bad Syntax: nginx: [emerg] "modsecurity_rules_file" directive Failed to allocate shared memory (1): Invalid argument in /opt/waf/nginx/etc/sites-enabled/domain.tld_nginx.conf:21 nginx: configuration file /opt/waf/nginx/etc/nginx.conf test failed**

Looking at line 21 of the config file, it just points to the 
**modsecurity_rules_file /opt/waf/nginx/etc/modsecurity_conf/domain.tld_modsec.conf file.**

I haven't made any changes to that particular site, today. I excluded some rules a few days ago and I was able to restart nginx without a problem. Now, the excluded rules are missing and I can't reload nginx. 

Like I said this is happening on a number of sites. I deleted the site thinking that I could just re-create it, but then this exact error started appearing on other sites. 

Additionally, the Attack entries are missing again. So, I'm guessing it's related to the logrotate script.

**Comment by ch-rigu** [comment]
> Bad Syntax: nginx: [emerg] "modsecurity_rules_file" directive **Failed to allocate shared memory** 

It looks like the stop signal in logrotate script sometime is not working or it's need more time to cool down and start again.

You can create an script that ensure to stop and start nginx in the log rotation phase
By now i can't work on this workaround, if you have a workaround that works good, please make a pull request.

Cheers.

**Comment by deeztek** [comment]
I'm not getting this error when I run the logrotate script. The script already ran at 1 a.m. this morning. I'm getting this error right now when I'm trying to reload nginx.

**Comment by ch-rigu** [comment]
yep, but i think is the consecuence of the manual stop and start of nginx, if complains with "**Failed to allocate shared memory**" is because something is wrong with the process, maybe the previous process is still running.
Check how many workers and process you have in the system.
Execute the logrotation script manually to check what's going on.

Otherwise you can disable logrotation (comment the line in the crontab) until a proper solution is found.

**Comment by deeztek** [comment]
Hi, I don't think this was due to previous processes not running. I rebooted the server and the error remained and it was complaining about 3 of my websites which were previously configured correctly but all of a sudden it didn't like the configuration anymore. So, I had to delete those sites and re-create them and it was fine again. Not sure, funny things hapenning. In the meantime, I have disabled the logrotate script from crontab. What is the long term consequences of doing that?

Thanks

**Comment by ch-rigu** [comment]
Hi, well if you disable logrotation, will cause that the audit log grow and grow and also the access and error logs (you will have to bkp the logs manually). This will have no effect on the waf itself. 
Cheers.

**Comment by ch-rigu** [comment]
this issue is part of modsecurity: [https://github.com/SpiderLabs/ModSecurity-nginx/issues/121](https://github.com/SpiderLabs/ModSecurity-nginx/issues/121)
the workaround it seems to use "copytruncate" in the logrotation configuration: [http://systemadmin.es/2014/05/logrotate-copytruncate-para-ficheros-que-no-se-dejan-rotar](http://systemadmin.es/2014/05/logrotate-copytruncate-para-ficheros-que-no-se-dejan-rotar)
