### ISSUE TITLE
Fail2ban

### ISSUE THREAD

**Issue by tai5555** [ITSec-Chile/Waf2Py#14]
Hi ! I have a query does it provide support to integrate utility like fail2ban (https://www.fail2ban.org/wiki/index.php/Main_Page). Alternatively how I can ban an ip via it? Please guide me. Thank you!

**Comment by ch-rigu** [comment]
Hi!, at the moment fail2ban is not integrated. I'm going to integrate it in a newer version, but it will take some time because WAF2PY will be re-written in a new framework (more fast and light).
You can configure fail2ban to watch nginx logs and ban attackers. But I don't have a receipt for this, maybe this guide you or give you an idea of how to:
https://snippets.aktagon.com/snippets/554-how-to-secure-an-nginx-server-with-fail2ban 

cheers.
