### ISSUE TITLE
Modsecurity 3 support

### ISSUE THREAD

**Issue by deeztek** [ITSec-Chile/Waf2Py#3]
Hi there,

Do you have a rough time-frame for when waf2py will support modsecurity 3?

Thanks

**Comment by ch-rigu** [comment]
Hi, we expect to release next version in about two weeks.

Cheers.
Chris.

**Comment by ch-rigu** [comment]
Hi, arun81

Well we are with a lot work since almost 3 months... :/ that's why the development is freezed by now.
the new version is ready but not published, need some fixes in some views.
in January we will publish the new version and we hope to continue with this development in a fluid way.

Cheers.
Chris.

**Comment by arun81** [comment]
Thanks Chris for the update ....

Cheers...
